version: 2
jobs:
  x86_64:
    docker:
      - image: staticfloat/julia_workerbase:centos6_9-x64
        environment:
          ARCH: x86_64
          CC: gcc
    steps: &steps
      - checkout
      - run:
          name: Build
          command: |
            #yum install -y patchelf
            make
      - run:
          name: Package
          command: |
            make package
            mkdir -p /tmp
            cp libopenspecfun-*.tar.gz /tmp
      - run:
          name: Test
          command: make test
      - store_artifacts:
          path: /tmp
  i686:
    docker:
      - image: staticfloat/julia_workerbase:centos6_9-x86
        environment:
          ARCH: i686
          CC: gcc
    steps: *steps
workflows:
  version: 2
  linux-builds:
    jobs:
      - x86_64
      - i686
